name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no -tt CloudAdmin@134.17.14.73 <<'CMD'
            cd C:\\webserver\\htdocs\\lk-ui-app
            git pull
            npm ci
            npm run build
            pm2 restart ecosystem.config.js
CMD
EOF
